### ISSUE TITLE
having issues

### ISSUE THREAD

**Issue by marieALaporte** [balhoff/dosdp-scala#5]
Nothing seems to be happening when I run the following command:
dosdp-scala --template=eq.yaml --print-query

This is my eq.yaml file:

> pattern_name: to/eq
> classes: []
> 
> relations:
>   part of: BFO_0000050
>   inheres in: RO_0000052
> 
> vars: 
>   attribute: "'Thing'"
>   entity: "'Thing'"
> 
> name:
>   text: "%s %s"
>   vars:
>     - entity
>     - attribute
> 
> def: 
>   text: "The %s of a %s."
>   vars:
>     - attribute
>     - entity
> 
> equivalentTo: 
>   text: "%s and 'inheres in' some %s"
>   vars:
>     - attribute
>     - entity

I was able to print the query when I used the exposure_to_radiation.yaml file that Chris used.

I am obviously missing something here but I don't know what. Any clue?

**Comment by balhoff** [comment]
There are a couple of problems that you are running into. First, the parsing is kind of strict and it is not expecting an array as the value of `classes`. You can fix that by putting a key and value there instead of `[]`. That will help fix the other problem, which is that the program doesn't know what 'Thing' refers to. I do, but it isn't built in (maybe it should be—I will check the spec and/or @dosumis. So you can do:

```yaml
classes:
  Thing: http://www.w3.org/2002/07/owl#Thing
```

One other thing: @cmungall had trouble when the pattern name contained a slash. For the time being you may want to remove it before generating the query. I will work on handling that better as well.

**Comment by marieALaporte** [comment]
Thanks. It works fine now.

**Comment by dosumis** [comment]
> First, the parsing is kind of strict and it is not expecting an array as the value of classes.

We should get testing via the JSON-LD schema up and running.  Would easily catch things like this.    Would be great if we could come up with a simple way to run validation as a service.

**Comment by cmungall** [comment]
Here's how we're testing for metazoan phenotypes: https://github.com/obophenotype/upheno/blob/master/src/patterns/Makefile#L1-L4

@marieALaporte we can adapt this for the TO ones.

**Comment by cmungall** [comment]
@balhoff I think this can be closed now
